USE [master]
GO

/****** Object:  Database [BookLibrary]    Script Date: 11.09.2023 09:51:15 ******/
CREATE DATABASE [BookLibrary]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BookLibrary', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\BookLibrary.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BookLibrary_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\BookLibrary_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookLibrary].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BookLibrary] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BookLibrary] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BookLibrary] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BookLibrary] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BookLibrary] SET ARITHABORT OFF 
GO

ALTER DATABASE [BookLibrary] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BookLibrary] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BookLibrary] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BookLibrary] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BookLibrary] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BookLibrary] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BookLibrary] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BookLibrary] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BookLibrary] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BookLibrary] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BookLibrary] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BookLibrary] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BookLibrary] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BookLibrary] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BookLibrary] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BookLibrary] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BookLibrary] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BookLibrary] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BookLibrary] SET  MULTI_USER 
GO

ALTER DATABASE [BookLibrary] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BookLibrary] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BookLibrary] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BookLibrary] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BookLibrary] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BookLibrary] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BookLibrary] SET QUERY_STORE = ON
GO

ALTER DATABASE [BookLibrary] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200)
GO

ALTER DATABASE [BookLibrary] SET  READ_WRITE 
GO

USE [BookLibrary]
GO

CREATE TABLE [dbo].[Books](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Writer] [varchar](50) NOT NULL,
	[Genre] [varchar](50) NOT NULL,
	[PageNumber] [varchar](50) NOT NULL,
	[Date_] [date] NOT NULL,
 CONSTRAINT [PK_BOOKS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[Customers](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FkBookId] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Surname] [varchar](50) NOT NULL,
	[Age] [smallint] NULL,
	[Male] [bit] NULL,
	[CreateDate] [date] NOT NULL,
	[TelNr] [varchar](15) NULL,
 CONSTRAINT [PK_CUSTOMERS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Customers] ADD  CONSTRAINT [DF_CUSTOMERS_CREATEDDATE]  DEFAULT (getdate()) FOR [CreateDate]
GO

ALTER TABLE [dbo].[Customers]  WITH CHECK ADD  CONSTRAINT [FK__Customers__FkBoo__440B1D61] FOREIGN KEY([FkBookId])
REFERENCES [dbo].[Books] ([ID])
GO

ALTER TABLE [dbo].[Customers] CHECK CONSTRAINT [FK__Customers__FkBoo__440B1D61]

CREATE TABLE [dbo].[Reservations](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BookId] [int] NOT NULL,
	[CustomerId] [int] NOT NULL,
	[DateTake] [date] NOT NULL,
	[DateReturn] [date] NOT NULL,
 CONSTRAINT [PK_RESERVATIONS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Reservations]  WITH CHECK ADD  CONSTRAINT [FK__Reservati__BookI__4316F928] FOREIGN KEY([BookId])
REFERENCES [dbo].[Books] ([ID])
GO

ALTER TABLE [dbo].[Reservations] CHECK CONSTRAINT [FK__Reservati__BookI__4316F928]
GO

ALTER TABLE [dbo].[Reservations]  WITH CHECK ADD FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customers] ([ID])
GO

ALTER TABLE [dbo].[Reservations]  WITH CHECK ADD  CONSTRAINT [FK_RESERVATIONS_RESERVATIONS] FOREIGN KEY([ID])
REFERENCES [dbo].[Reservations] ([ID])
GO

ALTER TABLE [dbo].[Reservations] CHECK CONSTRAINT [FK_RESERVATIONS_RESERVATIONS]